<a href="https://colab.research.google.com/github/flizzer/NumPy-Learning/blob/main/FourthBrainProgrammingChallengePractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Back-end Challenge

In the Python file, write a program to perform a GET request on the route https://coderbyte.com/api/challenges/json/age-counting which contains a data key and the value is a string which contains items in the format: key=STRING, age=INTEGER. Your goal is to count how many items exist that have an age equal to or greater than 50, and print this final value.

**Example Input**

{"data":"key=IAfpK, age=58, key=WNVdi, age=64, key=jp9zt, age=47"}

**Example Output**

2

**Given Code:**

```
import requests
import numpy as np
import pandas as pd

r = requests.get('https://coderbyte.com/api/challenges/json/age-counting')
print(len(r.json()['data']))


Python version
--------------
3.8.3 [GCC 8.3.0]

Packages installed
------------------
boto3
numpy
pandas
requests
scikit-learn
scipy

output logs will appear here
```




### Imports and setup based off of givens...

In [ ]:
import requests
import numpy as np
import pandas as pd

In [ ]:
r = requests.get('https://coderbyte.com/api/challenges/json/age-counting')
print(len(r.json()['data']))

5660


In [ ]:
age_data = r.json()['data']
type(age_data)

str

In [ ]:
age_data

'key=IAfpK, age=58, key=WNVdi, age=64, key=jp9zt, age=47, key=0Sr4C, age=68, key=CGEqo, age=76, key=IxKVQ, age=79, key=eD221, age=29, key=XZbHV, age=32, key=k1SN5, age=88, key=4SCsU, age=65, key=q3kG6, age=33, key=MGQpf, age=13, key=Kj6xW, age=14, key=tg2VM, age=30, key=WSnCU, age=24, key=f1Vvz, age=46, key=dOS7A, age=72, key=tDojg, age=82, key=nZyJA, age=48, key=R8JTk, age=29, key=005Ot, age=66, key=HHROm, age=12, key=5yzG8, age=51, key=xMJ5D, age=38, key=TXtVu, age=82, key=Hz38B, age=84, key=WfObU, age=27, key=mmqYB, age=14, key=4Z3Ay, age=62, key=x3B0i, age=55, key=QCiQB, age=72, key=zGtmR, age=66, key=nlIN9, age=8, key=hKalB, age=50, key=Na33O, age=17, key=jMeXm, age=15, key=OO2Mc, age=32, key=hhowx, age=34, key=gLMJf, age=60, key=PblX6, age=66, key=8Vm5W, age=22, key=oZKd6, age=88, key=RXNfQ, age=25, key=3yy0p, age=64, key=FrQbL, age=80, key=vlUkk, age=55, key=DP8po, age=80, key=EroX6, age=84, key=3bsll, age=86, key=QhZjA, age=85, key=wm6uc, age=74, key=MC1FM, age=75, key=AMxZr, a

### Parse the CSV list...

In [ ]:
age_data_list = age_data.split(sep=",")
type(age_data_list)
age_data_list

In [ ]:
age_array = age_data_list

In [ ]:
len(age_data_list)

600

### Get every other value separated by commas so as to get the ages and not the keys.  The length should be 1/2 the size of the total length...

In [ ]:
ages = age_data_list[1::2]
print(len(ages))

300


In [ ]:
ages
type(ages)

list

### Use list comprehension to parse the string for the right-hand side of the "=" in order to get the age value...

In [ ]:
ages_new = [int(x.split("=")[1]) for x in ages]
print(ages_new)
print(str.format("type = {0}", type(ages_new)))

[58, 64, 47, 68, 76, 79, 29, 32, 88, 65, 33, 13, 14, 30, 24, 46, 72, 82, 48, 29, 66, 12, 51, 38, 82, 84, 27, 14, 62, 55, 72, 66, 8, 50, 17, 15, 32, 34, 60, 66, 22, 88, 25, 64, 80, 55, 80, 84, 86, 85, 74, 75, 64, 4, 41, 74, 13, 57, 33, 79, 2, 15, 77, 80, 51, 43, 30, 4, 7, 55, 88, 3, 1, 45, 79, 81, 12, 42, 6, 22, 62, 74, 75, 19, 60, 19, 11, 38, 39, 46, 3, 38, 0, 25, 46, 17, 68, 1, 9, 72, 88, 38, 70, 37, 77, 30, 73, 22, 88, 16, 73, 88, 12, 25, 13, 27, 33, 26, 10, 3, 14, 58, 66, 17, 46, 78, 33, 10, 18, 35, 58, 29, 6, 2, 64, 20, 73, 31, 76, 75, 86, 2, 18, 5, 63, 7, 71, 27, 72, 50, 48, 1, 49, 67, 87, 64, 83, 39, 27, 71, 18, 60, 13, 1, 1, 22, 47, 89, 33, 39, 14, 68, 47, 62, 66, 6, 55, 35, 58, 18, 48, 39, 45, 43, 59, 57, 4, 35, 33, 88, 24, 74, 81, 39, 5, 75, 20, 3, 32, 80, 39, 79, 47, 77, 89, 11, 37, 2, 40, 34, 2, 84, 11, 72, 65, 58, 79, 47, 10, 86, 53, 17, 76, 47, 67, 21, 41, 35, 3, 37, 67, 67, 71, 67, 65, 53, 41, 8, 43, 21, 55, 26, 57, 8, 8, 9, 60, 57, 15, 80, 37, 7, 18, 10, 17, 15, 53, 88, 

### Use another list comprehension to get all the ages >= 50 and sum 'em up...

In [ ]:
#counter = 0
greater_than_fifty = ([x for x in ages_new if x >= 50])
#[counter x for x in ages_new if x > 50]
#print(greater_than_fifty)
print(greater_than_fifty)
print(len(greater_than_fifty)) #128 ages are over or equal to 50

[58, 64, 68, 76, 79, 88, 65, 72, 82, 66, 51, 82, 84, 62, 55, 72, 66, 50, 60, 66, 88, 64, 80, 55, 80, 84, 86, 85, 74, 75, 64, 74, 57, 79, 77, 80, 51, 55, 88, 79, 81, 62, 74, 75, 60, 68, 72, 88, 70, 77, 73, 88, 73, 88, 58, 66, 78, 58, 64, 73, 76, 75, 86, 63, 71, 72, 50, 67, 87, 64, 83, 71, 60, 89, 68, 62, 66, 55, 58, 59, 57, 88, 74, 81, 75, 80, 79, 77, 89, 84, 72, 65, 58, 79, 86, 53, 76, 67, 67, 67, 71, 67, 65, 53, 55, 57, 60, 57, 80, 53, 88, 85, 56, 84, 87, 52, 84, 51, 50, 87, 51, 53, 66, 78, 82, 53, 60, 50]
128


## Matrix Challenge

Have the function MatrixChallenge(strArr) read strArr which will be an array of integers represented as strings. Within the array there will also be "<>" elements which represent break points. The array will make up a matrix where the (number of break points + 1) represents the number of rows. Here is an example of how strArr may look: ["1","0","1","<>","0","1","0","<>","1","0","1"]. There are two "<>", so 2 + 1 = 3. Therefore there will be three rows in the array and the contents will be row1=[1 0 1], row2=[0 1 0] and row3=[1 0 1]. Your program should take the given array of elements, create the proper matrix, and then determine whether the matrix is symmetric, in other words, if matrix M is equal to M transpose. If it is, return the string symmetric and if it isn't return the string not symmetric. A matrix may or may not be a square matrix and if this is the case you should return the string not possible. For the example above, your program should return symmetric. 

***Example 1***

**Input:**

 ["5","0","<>","0","5"] 

**Output:**

symmetric

***Example 2***

**Input:** 

["1","2","4","<>","2","1","1","<>","-4","1","-1"] 

**Output:** 

not symmetric

**Given Code:**

```
import requests
import numpy as np
import pandas as pd

def MatrixChallenge(strArr):

  # code goes here
  return strArr

# keep this function call here 
print MatrixChallenge(raw_input())



Python version
--------------
3.8.3 [GCC 8.3.0]

Packages installed
------------------
boto3
numpy
pandas
requests
scikit-learn
scipy

output logs will appear here
```


In [1]:
import requests
import numpy as np
import pandas as pd

In [4]:
type(strArray1)

list

In [5]:
rows = [x.split(',') for x in (',').join(strArray1).split('<>')]
rows

[['5', '0', ''], ['', '0', '5']]

In [66]:
rows2 = [x.split(',') for x in (',').join(strArray2).split('<>')]
rows2

[['1', '2', '4', ''], ['', '2', '1', '1', ''], ['', '-4', '1', '-1']]

In [85]:
def splitArray(strArray):
  return [x.split(',') for x in (',').join(strArray).split('<>')]

In [7]:
def removeEmpties(rows):
  for row in rows:
    for element in row:
      #print(element)
      if element == '':
        #print(row.index(element))
        row.remove(element)       
  return rows

In [68]:
rows_filtered = removeEmpties(rows)
rows_filtered_array = np.array(rows, dtype=int)
print(rows_filtered_array)
type(rows_filtered_array)

[[5 0]
 [0 5]]


numpy.ndarray

In [70]:
rows2

[['1', '2', '4'], ['2', '1', '1'], ['-4', '1', '-1']]

In [71]:
rows2_filtered = removeEmpties(rows2)
rows2_filtered

[['1', '2', '4'], ['2', '1', '1'], ['-4', '1', '-1']]

In [63]:
def CreateMatrices(rows_filtered):
  rows_filtered_array = np.array(rows_filtered, dtype=int)
  matrix = np.matrix(rows_filtered_array)
  matrix_transposed = matrix.transpose()
  return matrix, matrix_transposed

In [92]:
matrix1 = np.matrix(rows_filtered)
matrix1

matrix([['5', '0'],
        ['0', '5']], dtype='<U1')

In [11]:
matrix1_transposed = matrix1.transpose()
matrix1_transposed

matrix([['5', '0'],
        ['0', '5']], dtype='<U1')

### Check if matrix is square (len of rows = len of columns):

In [108]:
matrix1.shape[0] == matrix1.shape[1]

True

In [105]:
matrix1

matrix([['5', '0'],
        ['0', '5']], dtype='<U1')

In [106]:
matrix1.shape
#len(matrix1.shape[0])

(2, 2)

In [74]:
matrix2, matrix2_transposed = CreateMatrices(rows2_filtered)
print(matrix2, matrix2_transposed)

[[ 1  2  4]
 [ 2  1  1]
 [-4  1 -1]] [[ 1  2 -4]
 [ 2  1  1]
 [ 4  1 -1]]


In [25]:
rows_filtered[0]

['5', '0']

In [39]:
type(rows_filtered_array[0])

numpy.ndarray

In [40]:
np.allclose(rows_filtered_array[0], rows_filtered_array[1])


False

In [79]:
output = compareMatrices(matrix2, matrix2_transposed)
output

'not symmetric'

In [112]:
def compareMatrices(matrix, matrix_transposed):
  #if (matrix.shape[0] == matrix.shape[1]): #this doesn't make sense so I'm commenting it out -- bhd
    #return "not possible"
  #else:
    return "symmetric" if (np.allclose(matrix, matrix_transposed)) else "not symmetric"
  

## Putting it all together for the challenge...

### Test case 1:

In [113]:
strArray1 = ["5","0","<>","0","5"]
MatrixChallenge(strArray1)

'symmetric'

### Test case 2:

In [114]:
strArray2 = ["1","2","4","<>","2","1","1","<>","-4","1","-1"]
MatrixChallenge(strArray2)

'not symmetric'

In [88]:
def MatrixChallenge(strArr):
   # code goes here
   rows = splitArray(strArr)
   #print("1st set of rows: ", rows)
   rows = removeEmpties(rows)
   #print("2nd set of rows: ", rows)
   matrix1, matrix1_transposed = CreateMatrices(rows)
   #print(matrix1, matrix1_transposed)
   return compareMatrices(matrix1, matrix1_transposed)
   
   
   #return strArr #not needed now that we have the function defined -- bhd

# keep this function call here 
#print MatrixChallenge(input())