<a href="https://colab.research.google.com/github/flizzer/NumPy-Learning/blob/main/NumPyTesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = [[1,3,5],
     [7,9,11],
     [13,15,17]]

In [ ]:
B = [1,3,5]

In [ ]:
type(A)

list

In [ ]:
type(B)

list

In [ ]:

C_element_wise = A * B

TypeError: ignored

In [ ]:
C = np.dot(A,B)
C

array([ 35,  89, 143])

In [ ]:
D = np.identity(5)

In [ ]:
D

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
type(D)

numpy.ndarray

In [ ]:
D.size

25

In [ ]:
D.shape

(5, 5)

In [ ]:
C.size

3

In [ ]:
C.shape

(3,)

In [ ]:
X = np.asarray([[1,3,5],
     [7,9,11],
     [13,15,17]], dtype='int')

In [ ]:
type(X)

numpy.ndarray

In [ ]:
X_transpose = X.transpose()
X_transpose

array([[ 1,  7, 13],
       [ 3,  9, 15],
       [ 5, 11, 17]])

In [ ]:
X_inverse = np.invert(X)
X_inverse

array([[ -2,  -4,  -6],
       [ -8, -10, -12],
       [-14, -16, -18]])

In [ ]:
Y = np.asarray([1,3,5], dtype='int')

In [ ]:
type(Y)

numpy.ndarray

In [ ]:
Z = np.dot(X,Y)
Z

array([ 35,  89, 143])

In [ ]:
type(Z)

numpy.ndarray

In [ ]:
Z.shape

(3,)

In [ ]:
Z.size

3

In [ ]:
Z_element_wise = X * Y
Z_element_wise

array([[ 1,  9, 25],
       [ 7, 27, 55],
       [13, 45, 85]])

In [ ]:
type(Z_element_wise)

numpy.ndarray

In [ ]:
Z_element_wise.shape

(3, 3)

In [ ]:
Z_element_wise.size

9

In [ ]:
Z_element_wise.transpose()

array([[ 1,  7, 13],
       [ 9, 27, 45],
       [25, 55, 85]])

In [ ]:
Z_transpose = Z.transpose()
Z_transpose

array([ 35,  89, 143])

In [ ]:
Z_inverse = Z